services:
  postgres_test:
    image: pgvector/pgvector:0.8.1-pg17-trixie
    environment:
      POSTGRES_DB: testing_db
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Use a different port to avoid conflict with local dev DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sail -d testing_db"]
      interval: 2s
      timeout: 5s
      retries: 10
